Contest city
paulinhps/balta-blazor-challenge pull request #4
Opened 2023-12-15 05:16 UTC by alex-marafon

2023-12-15 22:50 UTC, paulinhps commented
@alex-marafon  muito bom, mas vamos conversar sobre as mudanças ^^

2023-12-15 23:50 UTC, paulinhps requested changes
@alex-marafon boa entraga, vamos equalizar tudo e podemos seguir

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Infraestructure/Data/Confgurations/CitiesConfiguration.cs
> +                city.CityName
@alex-marafon, para cidade não precisa ter uma chave primaria composta

Se notar existem cidades com nomes diferentes em diferentes estados.

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/Entities/City.cs
> +    public class City : Entity
@alex-marafon  a parte de modelagem de domínio ricos se perdeu aqui!

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Infraestructure/Data/Confgurations/CitiesConfiguration.cs
@alex-marafon  Vamos conversar sobre o motivo das mudanças!

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Infraestructure/Data/Confgurations/CitiesConfiguration.cs
> +            builder.ToTable("CIDADE");
@alex-marafon, seguindo a lógica seria bom o nome da tabela ficar no plural ^^

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/Entities/Contracts/CityContract.cs
> +            Requires()
@alex-marafon  tirou a cascata de validação já existente

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/Constants/ApiEndPointsPaths.cs
> +    public const string Cities = "/api/v1/cities";
Interessando notar que sempre colocamos paths e url fatiadas sem / no final 

`https://localhost:5000`✔
`https://localhost:5000/`❌

Isso é boas práticas pois a ideia é que a responsabilidade da concatenação de paths seja de onde está agregando

`/api/v1/todos`✔
`api/v1/todos` ❌

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/DataModels/CityModel.cs
> +            public string UfCode { get; set; }
@alex-marafon como seguimos a modelagem customizada do projeto, City tem um relação N - 1 com estado, então o que cidade vai receber como parâmetro ao criar é o id do estado.

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Api/Endpoints/Localities/CityEndpoints.cs
@alex-marafon  ficou bom, mas eu vi que a modelagem dos resultados de caso de usam deixou difícil identificar qual tipo de erro aconteceu para podermos retornar o status code correto. Com isso eu fiz algumas alteração que você pode ver no PR #5. Que vai melhor muito a padronização do retorno

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Commands/CreateCityCommand.cs
> +    public string UfCode { get; set; } = null;
@alex-marafon  o comando não é a modelagem da entidade em si, o modelo que definimos são duas entidade relacionadas, onde uma **Cidade** está em um **Estado**, um **Estado** contém muitas **Cidades**. No modelo temos então a implmentação 

~~~csharp
// Recorte da entidade City.cs
public int StateId {get ;} 
public State State {get; }
/...
~~~

Então o correto é passar o id do estado para o comando e não o código

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Commands/DeleteCityCommand.cs
> +public class DeleteCityCommand : CommandBase, IRequest<CommandResult>
@alex-marafon por padrão trocar o result para a interface `ICommandResult`

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Commands/DeleteCityCommand.cs
> +public class DeleteCityCommand : CommandBase, IRequest<CommandResult>
Lembrando que tem que mudar no Handler também

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Commands/UpdateCityCommand.cs
> +    public string IbgeCode { get; set; } = null;
@alex-marafon se vamos mudar o estado da cidade temos atender a uma regra

Mudou estado, mudou código.
Para mudar estado tem que passar o Id do novo estado.
O código IBGE vai ser modificado quando o estado alterar, pensando nisso, não deve usar o id do comando e alterar mas sim gerar o código dentro do caso de uso.
Depois que mudar precisa revalidar.

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Create/Handler.cs
> +        command.Validate();
@alex-marafon  para fazer um fast validation melhor, você pode fazer essa chamada dentro do construtor do comando.

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/Cities/Create/Handler.cs
@alex-marafon  eu percebi estava difícil de lidar com os diferentes tipos de erros e retorno então eu mudei um pouco como montar o retorno. Vou te mostrar quando fizer o code review do PR #5

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Commands/DeleteStateCommand.cs
@alex-marafon  precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Commands/UpdateStateCommand.cs
@alex-marafon precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Create/Handler.cs
@alex-marafon precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Delete/Handler.cs
@alex-marafon precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Extensions/StatesDataModelsExtensions.cs
@alex-marafon precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Application/LocalityContext/States/Update/Handler.cs
@alex-marafon precisa fazer o revest aqui! Está mudança não faz parte do criar Cidade

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/DataModels/CreateCityModel.cs
@alex-marafon Revisar as validações

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/DataModels/CityModel.cs
Este modelo é de retorno, um DTO, não precisa de anotação de validação

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/Queries/City/CityQueries.cs
@alex-marafon  revisar

2023-12-15 23:50 UTC, paulinhps commented on src/IbgeBlazor.Core/LocalityContext/Repositories/ICitiesRepository.cs
> +    Task<bool> IsExistsCityWithIdOrUf(string ibgeCode, string cityName);
@alex-marafon  só pesquisar cidade com o mesmo código.

2023-12-16 01:59 UTC, alex-marafon commented on src/IbgeBlazor.Core/LocalityContext/Repositories/ICitiesRepository.cs
> +    Task<bool> IsExistsCityWithIdOrUf(string ibgeCode, string cityName);
Então, aqui ia fala com vcs, pq na pratica state esta e outra tabela e na tabela Cidade temos o codigo de referencia do State.

2023-12-16 02:12 UTC, alex-marafon commented on src/IbgeBlazor.Core/LocalityContext/Entities/Contracts/CityContract.cs
> +            Requires()
@paulinhps então não é que tirei e que apresentou um erro e não consegui entender p/ resolver, deixei comentado para falar com vcs.

2023-12-17 18:13 UTC, paulinhps approved these changes
@alex-marafon GG! 🦾✨✨✨

2023-12-17 18:13 UTC, merged